# Data settings
data:
  data_path: "./data"
  save_path: "./checkpoints"
  save_freq: 50
  phase: "train"

# Model architecture
model:
  in_dim: 576
  z_dim: 2
  hidden_dim: 64
  num_layers: 2 
  activation: "tanh"

# Prior settings
prior:
  translation: false 
  theta_prior: 0.1
  dx_prior: 0.1

# Training settings
train:
  epochs: 200
  batch_size: 200
  optim_type: "Adam"
  learning_rate: 1.0e-4
  seed: 521

# Logging settings
logging:
  wandb: true 
  logger_name: "VAE_NF"
  log_level: "INFO"
  screen: true
