# Data settings
data:
  data_path: "./data"
  save_path: "./checkpoints"
  save_freq: 50
  phase: "train"

# Model architecture
model:
  z_dim: 2
  hidden_dim: 512
  num_layers: 1
  activation: "tanh"

# Prior settings
prior:
  translation: false
  theta_prior: 1.0
  dx_prior: 1.0

# Training settings
train:
  epochs: 100
  batch_size: 100
  learning_rate: 1.0e-3
  seed: 42

# Logging settings
logging:
  wandb: true
  logger_name: "VAE_NF"
  log_level: "INFO"
  screen: true
